version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${gahlyiij}
    ports:
      - '5432:5432'
  app:
    container_name: api-geral
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      